export const CREATE_ADDON_REQUEST = 'CREATE_ADDON_REQUEST'
export const CREATE_ADDON_SUCCESS = 'CREATE_ADDON_SUCCESS'
export const CREATE_ADDON_FAIL = 'CREATE_ADDON_FAIL'

export const ADDON_LIST_REQUEST = 'ADDON_LIST_REQUEST'
export const ADDON_LIST_SUCCESS = 'ADDON_LIST_SUCCESS'
export const ADDON_LIST_FAIL = 'ADDON_LIST_FAIL'
