export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

export const CART_DB_REQUEST = 'CART_DB_REQUEST'
export const CART_DB_SUCCESS = 'CART_DB_SUCCESS'
export const CART_DB_FAIL = 'CART_DB_FAIL'
export const CART_DB_RESET = 'CART_DB_RESET'

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST'
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS'
export const CART_LIST_FAIL = 'CART_LIST_FAIL'
