export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const CART_SAVE_SHIPPING_ADDRESS_REQUEST =
  'CART_SAVE_SHIPPING_ADDRESS_REQUEST'
export const CART_SAVE_SHIPPING_ADDRESS_SUCCESS =
  'CART_SAVE_SHIPPING_ADDRESS_SUCCESS'
export const CART_SAVE_SHIPPING_ADDRESS_FAIL = 'CART_SAVE_SHIPPING_ADDRESS_FAIL'
export const CART_SAVE_SHIPPING_ADDRESS_RESET =
  'CART_SAVE_SHIPPING_ADDRESS_RESET'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'
